### PR TITLE
Enhanced the UX by converting the constructors to their respective wiki links

### PR DESCRIPTION
**Pull request by ayush-wd**

### CODE REVIEW

**Comment by brombomb** [comment]
I believe a URL is included in the JSON. Not all contructors names link to their F1 team page. Please update the a href attribute to use the URL property instead of name.

**Comment by ayush-wd** [comment]
yes sir

**Comment by ayush-wd** [comment]
Changed the URL sir

**Comment by brombomb** [comment]
Thank you for the PR!

**Pull request merged**
